# Generated by Django 4.2.2 on 2023-06-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='number_of_table',
        ),
        migrations.AddField(
            model_name='tables',
            name='status_of_table',
            field=models.BooleanField(default=True),
        ),
    ]
