# Generated by Django 4.2.2 on 2023-07-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeorder', '0002_remove_tables_number_of_table_tables_status_of_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tables',
            name='table_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
