# Generated by Django 4.2.2 on 2023-07-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeorder', '0003_category_tables_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='status_of_table',
            field=models.BooleanField(default=False),
        ),
    ]
