# Generated by Django 4.2.2 on 2023-07-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeorder', '0005_alter_tables_status_of_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='number',
        ),
        migrations.AlterField(
            model_name='tables',
            name='status_of_table',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('items', models.ManyToManyField(blank=True, related_name='order', to='takeorder.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(related_name='item', to='takeorder.category'),
        ),
    ]
